lines = [
    "\n---\n",
    "\n## 1. retrieval/multistage_retriever.py\n\n",
    "### Bug P0 (DA FIX)\n\n",
    "| Van de | Muc do | De xuat fix | Can LLM |\n",
    "|--------|--------|-------------|----------|\n",
    "| metadata_candidates merge cuoi -> bi loai khi graph+faiss+bm25 > cap 500 | Cao | DA FIX: doi thu tu merge | Khong |\n\n",
    "**Test verify**: chatbot/tests/test_multistage_retriever_merge_order.py - 6/6 PASS.\n\n",
    "### Danh gia Hieu nang: Candidate Embedding Cache\n\n",
    "embedder_model.encode() tai Stage 3 ma hoa lai toan bo candidate moi lan goi.\n",
    "Khuyen nghi: Implement lazy LRU cache maxsize=5000 theo key (movie_link, version).\n\n",
    "---\n\n",
    "## 2. retrieval/retrieval_router.py\n\n",
    "| Van de | Muc do | De xuat fix | Can LLM |\n",
    "|--------|--------|-------------|----------|\n",
    "| trace['stage0_graph'] KeyError tiem an | Trung | Them setdefault | Khong |\n",
    "| filters dict bi mutate truc tiep (side effect) | Trung | Dung filters.copy() | Khong |\n\n",
    "---\n\n",
    "## 3. entity_extractor.py\n\n",
    "| Van de | Muc do | De xuat fix | Can LLM |\n",
    "|--------|--------|-------------|----------|\n",
    "| get_fuzzy_candidates() co @st.cache_data | Thap | Khong can fix | Khong |\n",
    "| is_refine_query() de false positive | Trung | Them context check | Khong |\n\n",
    "---\n\n",
    "## 4. retrieval/bm25_retriever.py\n\n",
    "| Van de | Muc do | De xuat fix | Can LLM |\n",
    "|--------|--------|-------------|----------|\n",
    "| TRANSLATION_MAP co entry trung key (sieu anh hung x2, vu tru x2) | Trung | Xoa bo entry trung | Khong |\n\n",
    "---\n\n",
    "## 5. similarity/weighted_similarity.py\n\n",
    "Kiem tra call sites doc lap:\n",
    "- run_eval.py va run_eval_v2.py goi truc tiep cac ham similarity nhung co guard rieng\n",
    "- KHONG co sai lech score trong evaluation scripts.\n\n",
    "| Van de | Muc do | De xuat fix | Can LLM |\n",
    "|--------|--------|-------------|----------|\n",
    "| compute_genre_similarity([],[]) tra 1.0 - unreachable trong prod nhung confusing | Thap | Them docstring | Khong |\n\n",
    "---\n\n",
    "## 6. graph/graph_query.py\n\n",
    "| Van de | Muc do | De xuat fix | Can LLM |\n",
    "|--------|--------|-------------|----------|\n",
    "| NaN rating: float('nan') or 0.0 tra nan -> sort khong on dinh | Trung | them check: 0.0 if (r!=r) else r | Khong |\n\n",
    "---\n\n",
    "## 7. tools.py\n\n",
    "| Van de | Muc do | De xuat fix | Can LLM |\n",
    "|--------|--------|-------------|----------|\n",
    "| country_aliases load moi lan goi | Trung | Dung lru_cache | Khong |\n",
    "| semantic_search_tool() tra df.copy() khi fail | Trung | Doi thanh DataFrame() | Khong |\n\n",
    "---\n\n",
    "## 8. feedback_logger.py (DA FIX)\n\n",
    "| Van de | Muc do | De xuat fix | Can LLM |\n",
    "|--------|--------|-------------|----------|\n",
    "| open(a) khong atomic tren Windows - race condition | Cao | DA FIX: threading.Lock | Khong |\n",
    "| Multi-process: threading.Lock khong du | Trung | Dung filelock khi scale | Khong |\n\n",
    "---\n\n",
    "## Tong hop\n\n",
    "### Da fix (2):\n",
    "1. multistage_retriever.py - Candidate merge order\n",
    "2. feedback_logger.py - Thread-safety\n\n",
    "### Nen fix sprint toi (6):\n",
    "3. retrieval_router.py - trace KeyError tiem an\n",
    "4. retrieval_router.py - filters dict mutation\n",
    "5. bm25_retriever.py - Duplicate TRANSLATION_MAP entries\n",
    "6. graph_query.py - NaN rating sort instability\n",
    "7. tools.py - semantic_search_tool inconsistent return\n",
    "8. tools.py - country_aliases cache missing\n\n",
    "### Thap/document only (2):\n",
    "9. weighted_similarity.py - 1.0 vs 0.0 empty convention\n",
    "10. entity_extractor.py - is_refine_query false positive\n",
]
with open('E:/Desktop/4/DAP391m/code/chatbot/AUDIT_REPORT_NON_LLM_MODULES.md', 'a', encoding='utf-8') as f:
    f.writelines(lines)
print('Done')
